name: team_7
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2  
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  hive_ce_flutter: ^2.3.3
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  json_annotation: ^4.9.0
  json_serializable: ^6.11.3
  dartz: ^0.10.1
  retrofit: ^4.9.1
  retrofit_generator: ^10.0.6
  pretty_dio_logger: ^1.4.0
  get_it: ^9.1.0
  go_router: ^17.0.0
  flutter_native_splash: ^2.4.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#F5F8FE"
  color_dark: "#0D0D0D"

  image: assets/images/splash_logo_light.png
  image_dark: assets/images/splash_logo_dark.png
  


  android: true
  ios: true
  web: false

  android_12:
    color: "#F5F8FE"
    color_dark: "#0D0D0D"

    image: assets/images/native_splash_logo_light.png
    image_dark: assets/images/native_splash_logo_dark.png
    
  
  
